export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const SET_ACCESS_TOKEN_LOADING = 'SET_ACCESS_TOKEN_LOADING'
export const SET_ACCESS_TOKEN_SUCCESS = 'SET_ACCESS_TOKEN_SUCCESS'
export const SET_ACCESS_TOKEN_ERROR = 'SET_ACCESS_TOKEN_ERROR'
